### PR TITLE
fix: plucked out hmac512 implementation, subbed hmac256 with HmacSha256

### PR DESCRIPTION
**Pull request by alexanderGalushka**
addressing this https://github.com/timonson/djwt/issues/6

### CODE REVIEW

**Comment by alexanderGalushka** [comment]
@timonson I've tested it locally, please take a look

**Comment by timonson** [comment]
I see your editor has added semicolons to almost all files. I don't really care because I want to apply the official *deno style guides* in the future anyways but it makes your commit unclear. Do you want to keep it this way?

**Comment by alexanderGalushka** [comment]
@timonson yeap, I have the linter tailored for TS therefore it adds semicolons, sorry for the confusion, should probably turned off the linter before committing. If you are OK with this I'd rather keep those semicolons :)

**Comment by alexanderGalushka** [comment]
I've also made the deno std to reference specific version, e.g. `std@v0.53.0` which is supposed to be a good practice.

**Comment by timonson** [comment]
Thank you @alexanderGalushka !

**Pull request merged**
